services:
  mysql:
    image: mysql:8.0.34
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

  postgres:
    image: postgres:13-alpine
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass

  gate-simulator:
    image: node:23
    ports:
      - '9999:9999'
    working_dir: /app
    volumes:
      - ./gate-simulator:/app
    command: npm start